sonar.projectKey=AdityaApte145_DevSecOps-Assignment2-Backend
sonar.organization=adityaapte145
sonar.projectName=Backend LMS

sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/tests/**,**/__pycache__/**

sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
